trigger:
  branches:
    include: 
      - develop
  paths:
    include:
      - 'notebooks/*'

variables:
  - group: adw-dev-cicd

  - name: vmImageName
    value: ubuntu-latest
  - name: notebooksPath
    value: "notebooks"

pool:
  vmImage: $(vmImageName)

stages:
  - stage: deploy_to_dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - template: "templates/template-cicd.yml"
        parameters:
          env: "Develop"
          environmentName: $(dev-environment-name)
          resourceGroupName: $(dev-resource-group-name)
          serviceConnection: $(dev-service-connection-name)
          databricksWorkspaceName: $(dev-adw-name)
          notebooksPath: $(notebooksPath)