trigger:
  branches:
    include: 
      - main
  paths:
    include:
      - 'notebooks/*'

variables:
  - group: adw-dev-cicd

  - name: vmImageName
    value: ubuntu-latest
  - name: notebooksPath
    value: "team-engineering/notebooks"

pool:
  vmImage: $(vmImageName)

stages:
  - template: "templates/cicd_template.yml"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    parameters:
      stageId: "deploy_to_dev"
      env: "Develop"
      environmentName: $(dev-environment-name)
      resourceGroupName: $(dev-resource-group-name)
      serviceConnection: $(dev-service-connection-name)
      notebooksPath: $(notebooksPath)