trigger:
  branches:
    include: 
      - main
  paths:
    include:
      - 'notebooks/*'

variables:
  - group: adw-prod-cicd

  - name: vmImageName
    value: ubuntu-latest
  - name: notebooksPath
    value: "team-engineering/notebooks"

pool:
  vmImage: $(vmImageName)

stages:
  - template: "templates/cicd_template.yml"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    parameters:
      stageId: "deploy_to_prod"
      env: "Production"
      environmentName: $(prod-environment-name)
      resourceGroupName: $(prod-resource-group-name)
      serviceConnection: $(prod-service-connection-name)
      notebooksPath: $(notebooksPath)