parameters:
  - name: env
    type: string
  - name: environmentName
    type: string
  - name: resourceGroupName
    type: string
  - name: serviceConnection
    type: string
  - name: notebooksPath
    type: string
  - name: databricksWorkspaceName
    type: string

jobs:
  - deployment: Deploy
    displayName: "Deploy to ${{parameters.env}} Environment"
    environment: ${{parameters.environmentName}}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{parameters.serviceConnection}}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az config set extension.use_dynamic_install=yes_without_promot

                  $databricksWorspace = (az resource list --resource-group ${{parameters.resourceGroupName}} --query "[?type=='Microsoft.Databricks/workspaces']" | ConvertFrom-Json)[0]
                  done